CREATE DATABASE IF NOT EXISTS clientRegister;

USE clientRegister;

CREATE TABLE IF NOT EXISTS clientData (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IP INT UNSIGNED,
    PORT SMALLINT UNSIGNED
);